-- Works table
CREATE TABLE public.works (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  status TEXT CHECK (status IN ('active', 'completed', 'archived')) DEFAULT 'active',
  user_id UUID REFERENCES auth.users(id)
);

-- Contributions table
CREATE TABLE public.contributions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_id BIGINT REFERENCES public.works(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id),
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.works ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contributions ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Works are viewable if public or by owner" ON public.works 
FOR SELECT USING (
  privacy = 'Public' OR 
  auth.uid() = created_by
);
CREATE POLICY "Public contributions are viewable by everyone" ON public.contributions FOR SELECT USING (true);

-- Authenticated users can insert works
CREATE POLICY "Authenticated users can insert works" ON public.works FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Authenticated users can insert contributions
CREATE POLICY "Authenticated users can insert contributions" ON public.contributions FOR INSERT WITH CHECK (auth.role() = 'authenticated');
