import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        black: "#07000B", // Natural Black
        white: "#F5F5F5", // White Smoke
        "literary-black": "#171717",
        paper: "#FAFAFA",
        "muted-ink": "#525252",
        "literary-gold": "#D4AF37",
        // New redesign colors
        "error-container": "#ffdad6",
        "deep-teal": "#134E4A",
        "on-primary-fixed": "#00201e",
        "surface-container": "#e9edff",
        "outline-variant": "#bfc8c6",
        tertiary: "#003630",
        primary: "#003633",
        "on-tertiary-fixed-variant": "#204e48",
        "mist-grey": "#E5E7EB",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#8ebdb4",
        "secondary-fixed-dim": "#e3c466",
        "inverse-primary": "#a1cfcb",
        "primary-fixed-dim": "#a1cfcb",
        "tertiary-fixed": "#bcece3",
        error: "#ba1a1a",
        "on-surface": "#141b2b",
        "surface-container-low": "#f1f3ff",
        "primary-fixed": "#bcece7",
        "on-secondary-fixed-variant": "#574500",
        outline: "#707977",
        "surface-container-highest": "#dce2f9",
        "surface-container-high": "#e1e8fe",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#776005",
        surface: "#faf9ff",
        "ink-charcoal": "#111827",
        "secondary-container": "#fddd7c",
        "secondary-fixed": "#ffe085",
        "on-background": "#141b2b",
        "tertiary-container": "#1e4d46",
        "on-tertiary-fixed": "#00201c",
        "accent-gold": "#D4AF37",
        "on-error-container": "#93000a",
        "inverse-surface": "#293041",
        "inverse-on-surface": "#edf0ff",
        "surface-dim": "#d3d9f0",
        "surface-variant": "#dce2f9",
        "on-surface-variant": "#404847",
        "surface-bright": "#faf9ff",
        "on-primary-container": "#8ebdb8",
        secondary: "#735c00",
        "tertiary-fixed-dim": "#a0d0c7",
        "on-error": "#ffffff",
        "paper-bg": "#F9FAFB",
        "on-primary-fixed-variant": "#204e4a",
        "surface-tint": "#396662",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#231b00",
        "primary-container": "#1f4d4a",
      },
      keyframes: {
        "subtle-zoom": {
          "0%": { transform: "scale(1.05)" },
          "100%": { transform: "scale(1.15)" },
        },
      },
      animation: {
        "subtle-zoom": "subtle-zoom 20s ease-in-out infinite alternate",
      },
      fontFamily: {
        quicksand: ["var(--font-quicksand)", "sans-serif"],
        "be-vietnam": ["var(--font-be-vietnam-next)", "sans-serif"],
        serif: ["Lora", "Playfair Display", "serif"],
        "body-md": ["beVietnamPro"],
        "display-lg": ["Gánh"],
        "headline-md": ["Gánh"],
        "headline-lg": ["Gánh"],
        caption: ["Be Vietnam Pro"],
        "label-md": ["beVietnamPro"],
        "body-lg": ["beVietnamPro"],
        "display-lg-mobile": ["Be Vietnam Pro"],
        "headline-lg-mobile": ["Gánh"],
        "label-sm": ["beVietnamPro"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "max-width-content": "720px",
        sm: "16px",
        lg: "40px",
        xl: "64px",
        "margin-mobile": "16px",
        md: "24px",
        "margin-desktop": "80px",
        xs: "8px",
        base: "4px",
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg-mobile": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
export default config;
// Force rebuild 2026-03-01
